### ISSUE TITLE
Any plans for socket.io 1.0 compatibility?

### ISSUE THREAD

**Issue by gabrielf** [strongloop/strong-cluster-socket.io-store#12]
It seems to me that socket.io 1.0 removes the store concept in favor of adaptors such as https://github.com/Automattic/socket.io-redis

If there any plans to update this module or is there another, newer module that I just haven't found?

**Comment by db-roberto** [comment]
Hello,

Is this related to this error I keep getting trying to run my app with this module and socket.io 1.3.5: 

util.js:634
  ctor.prototype = Object.create(superCtor.prototype, {
                                          ^
TypeError: Cannot read property 'prototype' of undefined
    at exports.inherits (util.js:634:43)
    at module.exports (/home/node/node_modules/strong-cluster-socket.io-store/lib/cluster-store.js:52:3)
    at Object.<anonymous> (/home/node/app.js:3:61)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

I ask because I only started getting this after I updated to 1.3.5 socket.io

**Comment by sam-github** [comment]
Yes. We'd accept a PR!

**Comment by bajtos** [comment]
> @sam-github We don't have any immediate plans, but if you have an idea how to make it work for 0.x and 1.0, would you like to send us a PR?

In case it is too difficult to support both 0.x and 1.x versions, I think we can afford to make a breaking change, drop support for socket.io 0.x and release the new version of this module as v1.0.0. (At the moment, we are at v0.1.x).

**Comment by sam-github** [comment]
I agree, supporting on socket.io v1.x seems fine to me.
